import { RepoSettingsBranches } from '../RepoSettingsBranches';
import { RepoSettingsGeneral } from './RepoSettingsGeneral';
import {
    ActionsGeneralPanel,
    ActionsOidcPanel,
    ActionsPoliciesPanel,
    ActionsPolicyInsightsPanel,
    ActionsRunnersPanel,
    AdvancedSecurityPanel,
    CodespacesPanel,
    CollaboratorsPanelEnhanced,
    DeployKeysPanel,
    EmailNotificationsPanel,
    EnvironmentsPanel,
    LabSkillAppsPanel,
    ModerationInteractionPanel,
    ModerationReviewPanel,
    PagesPanel,
    PlanningAgentSuggestionsPanel,
    RulesetsPanel,
    SecretsActionsPanel,
    SecretsAgentsPanel,
    SecretsCodespacesPanel,
    SecretsDependabotPanel,
    SkillMateCloudAgentPanel,
    SkillMateCodeReviewPanel,
    SkillMateInternetPanel,
    SkillMateMcpPanel,
    TagsPanel,
    WebhooksPanel,
} from './RepoSettingsPanels';

export function getSettingsPanelComponent(section) {
    return SETTINGS_PANELS[section] ?? null;
}

export const SETTINGS_PANELS = {
    general: RepoSettingsGeneral,
    collaborators: CollaboratorsPanelEnhanced,
    branches: RepoSettingsBranches,
    'moderation-interaction': ModerationInteractionPanel,
    'moderation-review': ModerationReviewPanel,
    rulesets: RulesetsPanel,
    tags: TagsPanel,
    'actions-general': ActionsGeneralPanel,
    'actions-runners': ActionsRunnersPanel,
    'actions-policies': ActionsPoliciesPanel,
    'actions-policy-insights': ActionsPolicyInsightsPanel,
    'actions-oidc': ActionsOidcPanel,
    webhooks: WebhooksPanel,
    'skillmate-code-review': SkillMateCodeReviewPanel,
    'skillmate-cloud-agent': SkillMateCloudAgentPanel,
    'skillmate-internet': SkillMateInternetPanel,
    'skillmate-mcp': SkillMateMcpPanel,
    'planning-agent-suggestions': PlanningAgentSuggestionsPanel,
    environments: EnvironmentsPanel,
    codespaces: CodespacesPanel,
    pages: PagesPanel,
    'advanced-security': AdvancedSecurityPanel,
    'deploy-keys': DeployKeysPanel,
    'secrets-actions': SecretsActionsPanel,
    'secrets-agents': SecretsAgentsPanel,
    'secrets-codespaces': SecretsCodespacesPanel,
    'secrets-dependabot': SecretsDependabotPanel,
    'labskill-apps': LabSkillAppsPanel,
    'email-notifications': EmailNotificationsPanel,
};
